config/routes.rb
Rails.application.routes.draw do
  resources :project_team_employee_report_tasks

  resources :project_team_employee_reports

  resources :tasks

  resources :task_types

  resources :builds

  resources :releases

  resources :applications

  resources :report_statuses

  resources :project_team_employees

  resources :project_team_roles

  resources :project_teams

  resources :project_organizations

  resources :project_organization_types

  resources :projects

  resources :system_roles

  resources :users

  resources :employees

  resources :organizations
	post "organizations/:id/activate" => "organizations#activate", as: "activate_organization"
	post "organizations/:id/deactivate" => "organizations#deactivate", as: "deactivate_organization"
	post "organizations/:id/do_delete" => "organizations#do_delete", as: "do_delete_organization"
	post "organizations/:id/undo_delete" => "organizations#undo_delete", as: "undo_delete_organization"

	get 'home/index'

	resources :users

	resources :roles

	resources :employers
	post "employers/:id/activate" => "employers#activate", as: "activate_employer"
	post "employers/:id/deactivate" => "employers#deactivate", as: "deactivate_employer"
	post "employers/:id/do_delete" => "employers#do_delete", as: "do_delete_employer"
	post "employers/:id/undo_delete" => "employers#undo_delete", as: "undo_delete_employer"

	root 'home#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/build.rb
class Build < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :organization, polymorphic: true
  has_one :user
  has_many :project_team_employee_reports
  has_many :project_teams, through: :project_team_employees
  has_many :project_team_roles, through: :project_team_employees
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  # include Filterable
  # scope :contains, -> (name) { where("name like ?", "#{name}%") }
  # scope :is_active, -> (is_active) { where is_active: is_active }
  # scope :is_deleted, -> (is_deleted) { where is_deleted: is_deleted }
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :employees
	has_many :project_organizations
	has_many :projects, through: :project_organizations, source: :organization, source_type: "Project"
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_organizations
	has_many :organizations, through: :project_organizations, source: :project, source_type: "Organization"
	has_many :project_teams
	has_many :project_team_employee_reports
	has_many :tasks
	has_many :task_types
	has_many :report_statuses
	has_many :applications
	has_many :releases
	has_many :builds
end

app/models/project_team.rb
class ProjectTeam < ActiveRecord::Base
	belongs_to :project
	has_many :project_team_employee_reports
	has_many :project_team_roles
	has_many :employees, through: :project_team_employees
end

app/models/release.rb
class Release < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/report_status.rb
class ReportStatus < ActiveRecord::Base
	has_many :project_team_employee_reports
  belongs_to :project
end

app/models/system_role.rb
class SystemRole < ActiveRecord::Base
	has_many :users
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :task_type
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :created_by_user, :class_name => "User"
  belongs_to :updated_by_user, :class_name => "User"
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  belongs_to :project
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :employee
	belongs_to :system_role
	has_many :created_by_project_team_employee_report_tasks, :foreign_key => "created_by_user_id"
	has_many :created_by_project_team_employee_report_tasks, :foreign_key => "updated_by_user_id"
	has_many :created_by_tasks, :foreign_key => "created_by_user_id"
	has_many :created_by_tasks, :foreign_key => "updated_by_user_id"
end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :set_task_type, only: [:show, :edit, :update, :destroy]

  # GET /task_types
  # GET /task_types.json
  def index
    @task_types = TaskType.all
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
  end

  # GET /task_types/new
  def new
    @task_type = TaskType.new
  end

  # GET /task_types/1/edit
  def edit
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(task_type_params)

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render :show, status: :created, location: @task_type }
      else
        format.html { render :new }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_types/1
  # PATCH/PUT /task_types/1.json
  def update
    respond_to do |format|
      if @task_type.update(task_type_params)
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_type }
      else
        format.html { render :edit }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type.destroy
    respond_to do |format|
      format.html { redirect_to task_types_url, notice: 'Task type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_type
      @task_type = TaskType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_type_params
      params.require(:task_type).permit(:name, :description, :is_active, :is_deleted, :deleted_at)
    end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/task_types/_form.html.erb
<%= form_for(@task_type) do |f| %>
  <% if @task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_type.errors.count, "error") %> prohibited this task_type from being saved:</h2>

      <ul>
      <% @task_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :is_deleted %><br>
    <%= f.check_box :is_deleted %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br>
    <%= f.date_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_types/edit.html.erb
<h1>Editing task_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_type %> |
<%= link_to 'Back', task_types_path %>

app/views/task_types/index.html.erb
<h1>Listing task_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Is active</th>
      <th>Is deleted</th>
      <th>Deleted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_types.each do |task_type| %>
      <tr>
        <td><%= task_type.name %></td>
        <td><%= task_type.description %></td>
        <td><%= task_type.is_active %></td>
        <td><%= task_type.is_deleted %></td>
        <td><%= task_type.deleted_at %></td>
        <td><%= link_to 'Show', task_type %></td>
        <td><%= link_to 'Edit', edit_task_type_path(task_type) %></td>
        <td><%= link_to 'Destroy', task_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task type', new_task_type_path %>

app/views/task_types/new.html.erb
<h1>New task_type</h1>

<%= render 'form' %>

<%= link_to 'Back', task_types_path %>

app/views/task_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_type.description %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @task_type.is_active %>
</p>

<p>
  <strong>Is deleted:</strong>
  <%= @task_type.is_deleted %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @task_type.deleted_at %>
</p>

<%= link_to 'Edit', edit_task_type_path(@task_type) %> |
<%= link_to 'Back', task_types_path %>