config/routes.rb
Rails.application.routes.draw do
  resources :project_team_employee_report_tasks

  resources :project_team_employee_reports

  resources :tasks

  resources :task_types

  resources :builds

  resources :releases

  resources :applications

  resources :report_statuses

  resources :project_team_employees

  resources :project_team_roles

  resources :project_teams

  resources :project_organizations

  resources :project_organization_types

  resources :projects

  resources :system_roles

  resources :users

  resources :employees

  resources :organizations
	post "organizations/:id/activate" => "organizations#activate", as: "activate_organization"
	post "organizations/:id/deactivate" => "organizations#deactivate", as: "deactivate_organization"
	post "organizations/:id/do_delete" => "organizations#do_delete", as: "do_delete_organization"
	post "organizations/:id/undo_delete" => "organizations#undo_delete", as: "undo_delete_organization"

	get 'home/index'

	resources :users

	resources :roles

	resources :employers
	post "employers/:id/activate" => "employers#activate", as: "activate_employer"
	post "employers/:id/deactivate" => "employers#deactivate", as: "deactivate_employer"
	post "employers/:id/do_delete" => "employers#do_delete", as: "do_delete_employer"
	post "employers/:id/undo_delete" => "employers#undo_delete", as: "undo_delete_employer"

	root 'home#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/build.rb
class Build < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :organization, polymorphic: true
  has_one :user
  has_many :project_team_employee_reports
  has_many :project_teams, through: :project_team_employees
  has_many :project_team_roles, through: :project_team_employees
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  # include Filterable
  # scope :contains, -> (name) { where("name like ?", "#{name}%") }
  # scope :is_active, -> (is_active) { where is_active: is_active }
  # scope :is_deleted, -> (is_deleted) { where is_deleted: is_deleted }
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :employees
	has_many :project_organizations
	has_many :projects, through: :project_organizations, source: :organization, source_type: "Project"
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_organizations
	has_many :organizations, through: :project_organizations, source: :project, source_type: "Organization"
	has_many :project_teams
	has_many :project_team_employee_reports
	has_many :tasks
	has_many :task_types
	has_many :report_statuses
	has_many :applications
	has_many :releases
	has_many :builds
end

app/models/project_organization.rb
class ProjectOrganization < ActiveRecord::Base
  belongs_to :project, polymorphic: true
  belongs_to :organization, polymorphic: true
end

app/models/project_organization_type.rb
class ProjectOrganizationType < ActiveRecord::Base
	has_many :project_organizations
end

app/models/project_team.rb
class ProjectTeam < ActiveRecord::Base
	belongs_to :project
	has_many :project_team_employee_reports
	has_many :project_team_roles
	has_many :employees, through: :project_team_employees
end

app/models/release.rb
class Release < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/report_status.rb
class ReportStatus < ActiveRecord::Base
	has_many :project_team_employee_reports
  belongs_to :project
end

app/models/system_role.rb
class SystemRole < ActiveRecord::Base
	has_many :users
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :task_type
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :created_by_user, :class_name => "User"
  belongs_to :updated_by_user, :class_name => "User"
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  belongs_to :project
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :employee
	belongs_to :system_role
	has_many :created_by_project_team_employee_report_tasks, :foreign_key => "created_by_user_id"
	has_many :created_by_project_team_employee_report_tasks, :foreign_key => "updated_by_user_id"
	has_many :created_by_tasks, :foreign_key => "created_by_user_id"
	has_many :created_by_tasks, :foreign_key => "updated_by_user_id"
end

app/controllers/project_organizations_controller.rb
class ProjectOrganizationsController < ApplicationController
  before_action :set_project_organization, only: [:show, :edit, :update, :destroy]

  # GET /project_organizations
  # GET /project_organizations.json
  def index
    @project_organizations = ProjectOrganization.all
  end

  # GET /project_organizations/1
  # GET /project_organizations/1.json
  def show
  end

  # GET /project_organizations/new
  def new
    @project_organization = ProjectOrganization.new
  end

  # GET /project_organizations/1/edit
  def edit
  end

  # POST /project_organizations
  # POST /project_organizations.json
  def create
    @project_organization = ProjectOrganization.new(project_organization_params)

    respond_to do |format|
      if @project_organization.save
        format.html { redirect_to @project_organization, notice: 'Project organization was successfully created.' }
        format.json { render :show, status: :created, location: @project_organization }
      else
        format.html { render :new }
        format.json { render json: @project_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_organizations/1
  # PATCH/PUT /project_organizations/1.json
  def update
    respond_to do |format|
      if @project_organization.update(project_organization_params)
        format.html { redirect_to @project_organization, notice: 'Project organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_organization }
      else
        format.html { render :edit }
        format.json { render json: @project_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_organizations/1
  # DELETE /project_organizations/1.json
  def destroy
    @project_organization.destroy
    respond_to do |format|
      format.html { redirect_to project_organizations_url, notice: 'Project organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_organization
      @project_organization = ProjectOrganization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_organization_params
      params.require(:project_organization).permit(:project_id, :project_type, :organization_id, :organization_type, :project_organization_)
    end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_organizations_helper.rb
module ProjectOrganizationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/project_organizations/_form.html.erb
<%= form_for(@project_organization) do |f| %>
  <% if @project_organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_organization.errors.count, "error") %> prohibited this project_organization from being saved:</h2>

      <ul>
      <% @project_organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :organization_id %><br>
    <%= f.text_field :organization_id %>
  </div>
  <div class="field">
    <%= f.label :project_organization_ %><br>
    <%= f.text_field :project_organization_ %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_organizations/edit.html.erb
<h1>Editing project_organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_organization %> |
<%= link_to 'Back', project_organizations_path %>

app/views/project_organizations/index.html.erb
<h1>Listing project_organizations</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Organization</th>
      <th>Project organization </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_organizations.each do |project_organization| %>
      <tr>
        <td><%= project_organization.project %></td>
        <td><%= project_organization.organization %></td>
        <td><%= project_organization.project_organization_ %></td>
        <td><%= link_to 'Show', project_organization %></td>
        <td><%= link_to 'Edit', edit_project_organization_path(project_organization) %></td>
        <td><%= link_to 'Destroy', project_organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project organization', new_project_organization_path %>

app/views/project_organizations/new.html.erb
<h1>New project_organization</h1>

<%= render 'form' %>

<%= link_to 'Back', project_organizations_path %>

app/views/project_organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_organization.project %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @project_organization.organization %>
</p>

<p>
  <strong>Project organization :</strong>
  <%= @project_organization.project_organization_ %>
</p>

<%= link_to 'Edit', edit_project_organization_path(@project_organization) %> |
<%= link_to 'Back', project_organizations_path %>