config/routes.rb
Rails.application.routes.draw do
  resources :project_team_employee_report_tasks

  resources :project_team_employee_reports

  resources :tasks

  resources :task_types

  resources :builds

  resources :releases

  resources :applications

  resources :report_statuses

  resources :project_team_employees

  resources :project_team_roles

  resources :project_teams

  resources :project_organizations

  resources :project_organization_types

  resources :projects

  resources :system_roles

  resources :users

  resources :employees

  resources :organizations
	post "organizations/:id/activate" => "organizations#activate", as: "activate_organization"
	post "organizations/:id/deactivate" => "organizations#deactivate", as: "deactivate_organization"
	post "organizations/:id/do_delete" => "organizations#do_delete", as: "do_delete_organization"
	post "organizations/:id/undo_delete" => "organizations#undo_delete", as: "undo_delete_organization"

	get 'home/index'

	resources :users

	resources :roles

	resources :employers
	post "employers/:id/activate" => "employers#activate", as: "activate_employer"
	post "employers/:id/deactivate" => "employers#deactivate", as: "deactivate_employer"
	post "employers/:id/do_delete" => "employers#do_delete", as: "do_delete_employer"
	post "employers/:id/undo_delete" => "employers#undo_delete", as: "undo_delete_employer"

	root 'home#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/build.rb
class Build < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :organization, polymorphic: true
  has_one :user
  has_many :project_team_employee_reports
  has_many :project_teams, through: :project_team_employees
  has_many :project_team_roles, through: :project_team_employees
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  # include Filterable
  # scope :contains, -> (name) { where("name like ?", "#{name}%") }
  # scope :is_active, -> (is_active) { where is_active: is_active }
  # scope :is_deleted, -> (is_deleted) { where is_deleted: is_deleted }
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :employees
	has_many :project_organizations
	has_many :projects, through: :project_organizations, source: :organization, source_type: "Project"
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_organizations
	has_many :organizations, through: :project_organizations, source: :project, source_type: "Organization"
	has_many :project_teams
	has_many :project_team_employee_reports
	has_many :tasks
	has_many :task_types
	has_many :report_statuses
	has_many :applications
	has_many :releases
	has_many :builds
end

app/models/project_team.rb
class ProjectTeam < ActiveRecord::Base
	belongs_to :project
	has_many :project_team_employee_reports
	has_many :project_team_roles
	has_many :employees, through: :project_team_employees
end

app/models/project_team_employee_report_task.rb
class ProjectTeamEmployeeReportTask < ActiveRecord::Base
  belongs_to :project_team_employee_report
  belongs_to :task
  belongs_to :application
  belongs_to :release
  belongs_to :build
  belongs_to :created_by_user, :class_name => "User"
  belongs_to :updated_by_user, :class_name => "User"
end

app/models/release.rb
class Release < ActiveRecord::Base
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :project
end

app/models/report_status.rb
class ReportStatus < ActiveRecord::Base
	has_many :project_team_employee_reports
  belongs_to :project
end

app/models/system_role.rb
class SystemRole < ActiveRecord::Base
	has_many :users
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :task_type
  has_many :project_team_employee_reports, through: :project_team_employee_report_tasks
  belongs_to :created_by_user, :class_name => "User"
  belongs_to :updated_by_user, :class_name => "User"
end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  belongs_to :project
	has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :employee
	belongs_to :system_role
	has_many :created_by_project_team_employee_report_tasks, :foreign_key => "created_by_user_id"
	has_many :created_by_project_team_employee_report_tasks, :foreign_key => "updated_by_user_id"
	has_many :created_by_tasks, :foreign_key => "created_by_user_id"
	has_many :created_by_tasks, :foreign_key => "updated_by_user_id"
end

app/controllers/project_team_employee_report_tasks_controller.rb
class ProjectTeamEmployeeReportTasksController < ApplicationController
  before_action :set_project_team_employee_report_task, only: [:show, :edit, :update, :destroy]

  # GET /project_team_employee_report_tasks
  # GET /project_team_employee_report_tasks.json
  def index
    @project_team_employee_report_tasks = ProjectTeamEmployeeReportTask.all
  end

  # GET /project_team_employee_report_tasks/1
  # GET /project_team_employee_report_tasks/1.json
  def show
  end

  # GET /project_team_employee_report_tasks/new
  def new
    @project_team_employee_report_task = ProjectTeamEmployeeReportTask.new
  end

  # GET /project_team_employee_report_tasks/1/edit
  def edit
  end

  # POST /project_team_employee_report_tasks
  # POST /project_team_employee_report_tasks.json
  def create
    @project_team_employee_report_task = ProjectTeamEmployeeReportTask.new(project_team_employee_report_task_params)

    respond_to do |format|
      if @project_team_employee_report_task.save
        format.html { redirect_to @project_team_employee_report_task, notice: 'Project team employee report task was successfully created.' }
        format.json { render :show, status: :created, location: @project_team_employee_report_task }
      else
        format.html { render :new }
        format.json { render json: @project_team_employee_report_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_team_employee_report_tasks/1
  # PATCH/PUT /project_team_employee_report_tasks/1.json
  def update
    respond_to do |format|
      if @project_team_employee_report_task.update(project_team_employee_report_task_params)
        format.html { redirect_to @project_team_employee_report_task, notice: 'Project team employee report task was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_team_employee_report_task }
      else
        format.html { render :edit }
        format.json { render json: @project_team_employee_report_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_team_employee_report_tasks/1
  # DELETE /project_team_employee_report_tasks/1.json
  def destroy
    @project_team_employee_report_task.destroy
    respond_to do |format|
      format.html { redirect_to project_team_employee_report_tasks_url, notice: 'Project team employee report task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_team_employee_report_task
      @project_team_employee_report_task = ProjectTeamEmployeeReportTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_team_employee_report_task_params
      params.require(:project_team_employee_report_task).permit(:project_team_employee_report_id, :work_date, :work_hours, :task_id, :application_id, :release_id, :build_id, :created_by, :updated_by)
    end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_team_employee_report_tasks_helper.rb
module ProjectTeamEmployeeReportTasksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/project_team_employee_report_tasks/_form.html.erb
<%= form_for(@project_team_employee_report_task) do |f| %>
  <% if @project_team_employee_report_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_team_employee_report_task.errors.count, "error") %> prohibited this project_team_employee_report_task from being saved:</h2>

      <ul>
      <% @project_team_employee_report_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_team_employee_report_id %><br>
    <%= f.text_field :project_team_employee_report_id %>
  </div>
  <div class="field">
    <%= f.label :work_date %><br>
    <%= f.date_select :work_date %>
  </div>
  <div class="field">
    <%= f.label :work_hours %><br>
    <%= f.text_field :work_hours %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.text_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :application_id %><br>
    <%= f.text_field :application_id %>
  </div>
  <div class="field">
    <%= f.label :release_id %><br>
    <%= f.text_field :release_id %>
  </div>
  <div class="field">
    <%= f.label :build_id %><br>
    <%= f.text_field :build_id %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.text_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_team_employee_report_tasks/edit.html.erb
<h1>Editing project_team_employee_report_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_team_employee_report_task %> |
<%= link_to 'Back', project_team_employee_report_tasks_path %>

app/views/project_team_employee_report_tasks/index.html.erb
<h1>Listing project_team_employee_report_tasks</h1>

<table>
  <thead>
    <tr>
      <th>Project team employee report</th>
      <th>Work date</th>
      <th>Work hours</th>
      <th>Task</th>
      <th>Application</th>
      <th>Release</th>
      <th>Build</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_team_employee_report_tasks.each do |project_team_employee_report_task| %>
      <tr>
        <td><%= project_team_employee_report_task.project_team_employee_report %></td>
        <td><%= project_team_employee_report_task.work_date %></td>
        <td><%= project_team_employee_report_task.work_hours %></td>
        <td><%= project_team_employee_report_task.task %></td>
        <td><%= project_team_employee_report_task.application %></td>
        <td><%= project_team_employee_report_task.release %></td>
        <td><%= project_team_employee_report_task.build %></td>
        <td><%= project_team_employee_report_task.created_by %></td>
        <td><%= project_team_employee_report_task.updated_by %></td>
        <td><%= link_to 'Show', project_team_employee_report_task %></td>
        <td><%= link_to 'Edit', edit_project_team_employee_report_task_path(project_team_employee_report_task) %></td>
        <td><%= link_to 'Destroy', project_team_employee_report_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project team employee report task', new_project_team_employee_report_task_path %>

app/views/project_team_employee_report_tasks/new.html.erb
<h1>New project_team_employee_report_task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_team_employee_report_tasks_path %>

app/views/project_team_employee_report_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project team employee report:</strong>
  <%= @project_team_employee_report_task.project_team_employee_report %>
</p>

<p>
  <strong>Work date:</strong>
  <%= @project_team_employee_report_task.work_date %>
</p>

<p>
  <strong>Work hours:</strong>
  <%= @project_team_employee_report_task.work_hours %>
</p>

<p>
  <strong>Task:</strong>
  <%= @project_team_employee_report_task.task %>
</p>

<p>
  <strong>Application:</strong>
  <%= @project_team_employee_report_task.application %>
</p>

<p>
  <strong>Release:</strong>
  <%= @project_team_employee_report_task.release %>
</p>

<p>
  <strong>Build:</strong>
  <%= @project_team_employee_report_task.build %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @project_team_employee_report_task.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @project_team_employee_report_task.updated_by %>
</p>

<%= link_to 'Edit', edit_project_team_employee_report_task_path(@project_team_employee_report_task) %> |
<%= link_to 'Back', project_team_employee_report_tasks_path %>